<embed src="https://harryso02.github.io/soka-certificate.pdf" type="application/pdf" />
<embed src="https://harryso02.github.io/expivotal-certificate.pdf" type="application/pdf" />
<embed src="https://harryso02.github.io/ethics-certificate.pdf" type="application/pdf" />
<embed src="https://harryso02.github.io/harryso_resume(220802).pdf" type="application/pdf" />
<embed src="https://harryso02.github.io/humanlib-certificate.pdf" type="application/pdf" />
